name: Release
on:
  create:
    tags:
      - v*
  workflow_dispatch:
jobs:
  package:
    runs-on: ${{ matrix.os }}
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

    strategy:
      matrix:
        os: [ ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Package Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          npm ci
          npm run build
          npx electron-builder --linux deb rpm --x64 --publish always
          npx electron-builder --linux AppImage --x64 --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
